"""Package per-scenario data into immutable zip archives + write manifest.json.

For each registered scenario (saint-petersburg / vasilievsky-island /
yuzhno-sakhalinsk) creates a zip archive whose root directory is the
scenario name. SHA256 + size for every archive land in ``data/manifest.json``,
which is the single source of truth for ``fetch_data.py`` and for the
GitHub-Releases mapping.

Usage:
    python scripts/package_data.py                     # package all
    python scripts/package_data.py --only saint-petersburg vasilievsky-island
    python scripts/package_data.py --out data/_releases
    python scripts/package_data.py --dry-run           # list what would be packed

Conventions:
- Zip root = ``<scenario_id>/`` (same as ``DATA_DIR/<scenario_id>`` layout).
- ``acc_mx.pickle``, ``blocks_with_services.gpkg``, graph artefacts: always
  included if present.
- ``outputs/`` excluded — runtime artefacts, regenerated by agent runs.
- ``*.tmp``, ``*.bak``, hidden dirs: excluded.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
import zipfile
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable

ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "data"
DEFAULT_OUT = DATA_DIR / "_releases"
MANIFEST_PATH = DATA_DIR / "manifest.json"
SCHEMA_VERSION = 1

EXCLUDE_DIRS = {"outputs", "__pycache__", ".ipynb_checkpoints", "_releases"}
EXCLUDE_GLOBS = ("*.tmp", "*.bak", "*.swp", "._*", ".DS_Store", "Thumbs.db")


@dataclass
class ScenarioSpec:
    """Per-scenario packaging contract."""

    scenario_id: str
    description: str
    source_globs: list[str] = field(default_factory=list)
    notes: list[str] = field(default_factory=list)


SCENARIOS: list[ScenarioSpec] = [
    ScenarioSpec(
        scenario_id="saint-petersburg",
        description=(
            "Санкт-Петербург: ~494 МБ. Полный набор для provision + scenario. "
            "acc_mx.pickle и blocks_with_services.gpkg готовы."
        ),
        source_globs=[
            "saint-petersburg/data/**",
        ],
        notes=[
            "compute_road_congestion НЕ готов (нет graph_drive/b2n/n2n).",
            "Для road_congestion: MCP-tool prepare_road_congestion_inputs (Overpass через blocksnet.relations.get_accessibility_graph).",
        ],
    ),
    ScenarioSpec(
        scenario_id="vasilievsky-island",
        description=(
            "Васильевский остров (СПб): ~140 МБ. Готовые road_congestion inputs, "
            "blocks_with_services.gpkg в корне сценария. acc_mx.pickle "
            "ОТСУТСТВУЕТ — provision-расчёты не работают."
        ),
        source_globs=[
            "vasilievsky-island/**",
        ],
        notes=[
            "acc_mx.pickle отсутствует → compute_service_provision, "
            "compute_scenario_provision, recommend_blocks_for_services упадут.",
            "compute_road_congestion полностью готов (graph_drive + b2n + n2n).",
            "Запуск: DATA_DIR=data/vasilievsky-island python -m blocksnet_agent.",
        ],
    ),
    ScenarioSpec(
        scenario_id="yuzhno-sakhalinsk",
        description=(
            "Южно-Сахалинск: ~27 МБ. Полный provision-набор: "
            "blocks_with_services.gpkg (903 блока, 60+ сервисов) + acc_mx.pickle готовы. "
            "road_congestion inputs отсутствуют."
        ),
        source_globs=[
            "yuzhno-sakhalinsk/data/**",
        ],
        notes=[
                    "compute_road_congestion НЕ готов (нет graph_drive/b2n/n2n).",
                    "blocks_with_services.gpkg = переименованный blocks.gpkg (содержит всё для provision).",
                    "Для road_congestion: MCP-tool prepare_road_congestion_inputs (Overpass через blocksnet.relations.get_accessibility_graph).",
                ],
    ),
]


def _iter_files(scenario: ScenarioSpec) -> Iterable[Path]:
    """Yield source files for a scenario, applying excludes.

    Supports ``**`` in glob patterns. The pattern root is ``data/``.
    """
    seen: set[Path] = set()
    for pattern in scenario.source_globs:
        if "**" in pattern:
            # Recursive: pattern like "saint-petersburg/data/**" matches all
            # descendants including files in subdirectories.
            base = pattern.split("**", 1)[0].rstrip("/")
            base_path = DATA_DIR / base
            for path in base_path.rglob("*"):
                if path.is_file():
                    seen.add(path)
                    yield path
        else:
            for path in DATA_DIR.glob(pattern):
                if path.is_file():
                    seen.add(path)
                    yield path
    # Always include README at <scenario>/README.md if present (idempotent).
    readme = DATA_DIR / scenario.scenario_id / "README.md"
    if readme.is_file() and readme not in seen:
        yield readme


def _is_excluded(rel: Path) -> bool:
    parts = rel.parts
    if any(p in EXCLUDE_DIRS for p in parts):
        return True
    name = rel.name
    for glob in EXCLUDE_GLOBS:
        if Path(name).match(glob):
            return True
    return False


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def _human_size(n: int) -> str:
    for unit in ("B", "KB", "MB", "GB"):
        if n < 1024:
            return f"{n:.1f} {unit}"
        n /= 1024  # type: ignore[assignment]
    return f"{n:.1f} TB"


def package_scenario(
    scenario: ScenarioSpec,
    out_dir: Path,
    *,
    dry_run: bool = False,
) -> dict:
    """Zip one scenario, return manifest entry."""
    out_dir.mkdir(parents=True, exist_ok=True)
    archive_name = f"{scenario.scenario_id}-data.zip"
    archive_path = out_dir / archive_name

    files: list[dict] = []
    total_uncompressed = 0
    file_list = sorted(_iter_files(scenario))

    for src in file_list:
        rel = src.relative_to(DATA_DIR)
        if _is_excluded(rel):
            continue
        size = src.stat().st_size
        total_uncompressed += size
        files.append({"path": str(rel), "size_bytes": size})

    print(
        f"[{scenario.scenario_id}] {len(files)} files, "
        f"{_human_size(total_uncompressed)} uncompressed"
    )

    if dry_run:
        return {
            "scenario_id": scenario.scenario_id,
            "description": scenario.description,
            "archive": archive_name,
            "files": files,
            "notes": scenario.notes,
            "dry_run": True,
        }

    with zipfile.ZipFile(archive_path, "w", zipfile.ZIP_DEFLATED, compresslevel=6) as z:
        for src, entry in zip(
            (DATA_DIR / f["path"] for f in files), files
        ):
            # Arcname preserves scenario-rooted layout: e.g. saint-petersburg/data/...
            z.write(src, arcname=src.relative_to(DATA_DIR).as_posix())

    size = archive_path.stat().st_size
    sha = _sha256(archive_path)
    print(f"  → {archive_path.relative_to(ROOT)} ({_human_size(size)}, sha256={sha[:12]}…)")

    return {
        "scenario_id": scenario.scenario_id,
        "description": scenario.description,
        "archive": archive_name,
        "size_bytes": size,
        "size_uncompressed_bytes": total_uncompressed,
        "sha256": sha,
        "file_count": len(files),
        "files": files,
        "notes": scenario.notes,
    }


def write_manifest(entries: list[dict]) -> Path:
    manifest = {
        "schema_version": SCHEMA_VERSION,
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "generator": "scripts/package_data.py",
        "scenarios": {e["scenario_id"]: e for e in entries},
    }
    MANIFEST_PATH.write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    return MANIFEST_PATH


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Package per-scenario data into zip archives + manifest.json",
    )
    parser.add_argument("--only", nargs="+", help="Pack only these scenario_ids")
    parser.add_argument(
        "--out", type=Path, default=DEFAULT_OUT,
        help=f"Output directory for archives (default: {DEFAULT_OUT})",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="List what would be packed, do not write archives",
    )
    args = parser.parse_args()

    scenarios = SCENARIOS
    if args.only:
        wanted = set(args.only)
        scenarios = [s for s in SCENARIOS if s.scenario_id in wanted]
        if not scenarios:
            print(f"no scenarios matched {args.only!r}", file=sys.stderr)
            return 2

    if not args.dry_run:
        args.out.mkdir(parents=True, exist_ok=True)

    entries = [package_scenario(s, args.out, dry_run=args.dry_run) for s in scenarios]

    if args.dry_run:
        print("\n[dry-run] manifest NOT written")
        return 0

    manifest_path = write_manifest(entries)
    print(f"\n[manifest] {manifest_path.relative_to(ROOT)} ({len(entries)} scenarios)")
    return 0


if __name__ == "__main__":
    sys.exit(main())